POST http://localhost:4000/kittyprofile
Content-Type: application/json

    {
     "heitiKattar": "Magnús",
     "kyn": "KK",
     "aldur":38,
     "ormerking":222522222222,
     "litur":"grænn",
     "heitiEigandi":"Jhonny Mcbain",
     "ktEigandi":"87679383434",
     "heimilisfangEigandi":"Kársnes",
     "simiEigandi":"5819345",
     "athugamsemdir":"Ekki gefa tunfisk"
    }

###

