POST http://localhost:4000/kittyprofile
Content-Type: application/json

    {
     "heitiKattar": "Smári",
     "kyn": "KK",
     "aldur":38,
     "ormerking":222222222222,
     "litur":"gulur",
     "heitiEigandi":"Pedro",
     "ktEigandi":"87679343434",
     "heimilisfangEigandi":"Hafnafjörður",
     "simiEigandi":"5812345",
     "athugamsemdir":"mjáwesome"
    }

###

DELETE http://localhost:4000/api/_id
Content-Type: application/json
